bannerTitle : 'OUR SERVICES'
bannerDescription : 'We donâ€™t like to be everything to everyone. We would rather be something to someone, you. Bespoke design services from the house of Little Brahma. With each of our cosmic diagrams (Mandala), we commit to instinctive work and transformational execution. 
"We meditate on these all-day long"'
